
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhzxosauasserghpxbql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oenhvc2F1YXNzZXJnaHB4YnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MTc2NDAsImV4cCI6MjA4MjM5MzY0MH0.eskdjSMlCKy_pwv6Nm9hRw8AFhm4VNSHz436BsZC6o8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
